providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
api:
  insecure: true
  dashboard: true
tracing:
  otlp:
    http:
      endpoint: http://jaeger:4318/v1/traces
metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
accessLog:
    filePath: /logs/access.log
    bufferingSize: 100


entryPoints:
  http:
    address: ":80"
  dns-tcp:
    address: ":53/tcp"
  dns-udp:
    address: ":53/udp"
