providers:
  file:
    filename: /etc/traefik/middlewares.yml
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
api:
  insecure: true
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: a.mancuso@alumno.um.edu.ar
      storage: acme.json
      httpChallenge:
        entryPoint: http
tracing:
  otlp:
    http:
      endpoint: http://jaeger:4318/v1/traces
metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
accessLog:
  filePath: /logs/access.log
  bufferingSize: 100

entryPoints:
  http:
    address: ":80"
#    http:
#      redirections:
#        entryPoint:
#          to: https
#          scheme: https
#          permanent: true
  https:
    address: ":443"
  dns-tcp:
    address: ":53/tcp"
  dns-udp:
    address: ":53/udp"
