version: "3.8"
services:
  reverse_proxie:
    image: traefik:v3
    container_name: reverse_proxie
    ports:
      - "8080:8080"
      - "9080:80"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/logs"

    restart: unless-stopped
    networks:
      - openwrt-lan
      - backend-network
networks:
  openwrt-lan:
  backend-network:

