services:
  auth_db:
    image: postgres:alpine
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./keycloak-data:/var/lib/postgresql/data
    networks:
      - backend-network

  authentication:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8180:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://auth_db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: false
      KC_PROXY: edge
    command: start-dev
    depends_on:
      - auth_db
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.keycloak.rule=Host(`auth.docker.localhost`)"
#      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    networks:
      - backend-network