services:

  dns:
    image: powerdns/pdns-recursor-52
    container_name: dns
    environment:
      - PDNS_RECURSOR_ALLOW_FROM=0.0.0.0/0
    networks:
      - backend-network
    volumes:
      - ./pdns-recursor.conf:/etc/powerdns-recursor/recursor.conf
    ports:
      - "5301:53/tcp"
      - "5301:53/udp"

networks:
  backend-network:
