services:
  dns:
    image: adguard/adguardhome
    container_name: dns
    ports:
      - "8053:53/tcp"
      - "8053:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dns.rule=PathPrefix(`/routerease/dns/`)"
      - "traefik.http.services.dns.loadbalancer.server.port=80"
    networks:
      - openwrt-lan
networks:
  openwrt-lan:
