services:
  mac-lookup:
    build: .
    container_name: mac-lookup
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mac-address.rule=PathPrefix(`/routerease/mac-address/`)"
      - "traefik.http.services.mac-address.loadbalancer.server.port=8080"
      - "traefik.http.routers.mac-address.tls=true"
      - "traefik.http.routers.mac-address.tls.certresolver=letsencrypt"
    networks:
      - backend-network
    restart: unless-stopped

networks:
  backend-network: