name: router-ease-api
services:
  reverse_proxie:
    extends:
      file: ReverseProxie/traefik-docker-compose.yaml
      service: reverse_proxie

  whoami:
    extends:
      file: ReverseProxie/traefik-docker-compose.yaml
      service: whoami


  dns:
    extends:
      file: DNS/powerdns-docker-compose.yaml
      service: dns


  go-proxie:
    extends:
      file: GO-Proxie/go-proxie-docker-compose.yaml
      service: go-proxie


  mac-lookup:
    extends:
      file: ./MACLookUp/mac-address-service-docker-compose.yml
      service: mac-lookup

  jaeger:
    extends:
      file: ./Observability/Jaeger/jaeger-docker-compose.yaml
      service: jaeger

  prometheus:
    extends:
      file: ./Observability/Prometheus/prometheus-docker-compose.yaml
      service: prometheus

  authentication:
    extends:
      file: ./Authentication/keycloak-docker-compose.yaml
      service: authentication

  auth_db:
    extends:
      file: ./Authentication/keycloak-docker-compose.yaml
      service: auth_db

  dns_db:
    extends:
      file: ./GO-Proxie/go-proxie-docker-compose.yaml
      service: dns_db

networks:
  openwrt-wan:
  backend-network:
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 172.20.0.0/24


# docker network create --subnet=172.20.0.0/24 backend-network
